# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00401575da11ecc0af14a0b32b77c1cb3cbe32f676b869632898588e7a569ab49912558633f7fc581b0aa32205e1b5961679f2eb25f5d13f6835e0987a82bdf0

test:
  secret_key_base: 4ab9a4a145495c8a2d9a15c665e0467871f9521fabea9121ebbed99565c22416a9e7dc60b4db23b3629e343b27e2db287e874bf19f5f1882ceef7bb8f2f04bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
